### ISSUE TITLE
Packager succeeded but did not create a package

### ISSUE THREAD

**Issue by KyrosKrane** [BigWigsMods/packager#136] opened 2022-09-05 02:40 UTC
Summary: I created two tags on the same commit, first an alpha tag, then a release tag. The alpha tag caused an alpha build; the release tag did not create a release at all.

Details:

Earlier today, I pushed a few commits to my addon and tagged them first as v14.0.2-alpha, then more commits, then v14.1.0-alpha. With each tag, the packager correctly built a package.

Here are the action logs for [v14.0.2-alpha](https://github.com/KyrosKrane/AnnoyingPopupRemover/actions/runs/2989581182) and [v14.1.0-alpha](https://github.com/KyrosKrane/AnnoyingPopupRemover/actions/runs/2990341136). Both built correctly and created zip files on both GitHub and Curseforge.

After reviewing v14.1.0-alpha, I determined no other changes were needed. I tagged the same commit as v14.1.0-release and pushed the tag. GitHub picked it up and ran the packager; [here's the log](https://github.com/KyrosKrane/AnnoyingPopupRemover/actions/runs/2990362181). The log shows the packager succeeded. But this time, it did not create a new GitHub release, did not create zip files, and didn't upload anywhere. Further, the log indicates that it picked up the alpha tag, not the release tag. (I have two different actions, based on the tag. The release action ran, but the packager script detected the alpha tag. My alphas only upload to Curseforge; releases upload to all the sites.)

In the past, I've done the same steps for other releases; you can see in the [git logs](https://github.com/KyrosKrane/AnnoyingPopupRemover/tags) how many commits have both an alpha and release tag. For example, both [v14.0.0-alpha](https://github.com/KyrosKrane/AnnoyingPopupRemover/releases/tag/v14.0.0-alpha) and [v14.0.0-release](https://github.com/KyrosKrane/AnnoyingPopupRemover/releases/tag/v14.0.0-release) are on the same [commit](https://github.com/KyrosKrane/AnnoyingPopupRemover/commit/e2cebc5c195736d1f1ac4b7f9ec893caaa977f99). It's always packaged the release normally.

To force it to create a new package, I made a trivial commit (changing a comment), tagged it as [v14.1.1-release](https://github.com/KyrosKrane/AnnoyingPopupRemover/actions/runs/2990392005), and pushed. That built correctly and created a package; however the changelog was only from v14.1.0-release, not from v14.0.0-release (the last release prior to these changes).

Any idea why the build for v14.1.0-release detected the alpha tag, not the release tag? And why it didn't end up creating a release zip file?

**Comment by nebularg** [comment] 2022-09-05 03:01
Are you using annotated tags?

**Comment by KyrosKrane** [comment] 2022-09-05 03:11
> Are you using annotated tags?

I'm not sure what that is. When I create a new tag, I do put the same value in the tag name and tag message, if that's what you mean. Example:
![image](https://user-images.githubusercontent.com/458727/188353545-d5e8f6d4-27cd-498c-8cf7-66bf9f6b8d7f.png)

**Comment by KyrosKrane** [comment] 2022-09-05 03:23
I just looked up the details. It's indeed an annotated tag, as I put a message and sign the tag. Confirmed on the git command line as well.

**Comment by nebularg** [comment] 2022-09-05 13:40
Yea, I really have no idea why it didn't use the release tag. It should have, the log shows that it was there. The [docs](https://git-scm.com/docs/git-describe#_search_strategy) say it should have been used.

I can't reproduce it, so I'm going to just blame github since the packager did what it was suppose to with the output it got from git.

**Comment by Nevcairiel** [comment] 2022-09-05 13:44
I assume this is from having two tags on the same commit, and git describe to generate the version was still using the original alpha tag, because why would it have any preference to take one over the other if both are at the same point in history?

**Comment by nebularg** [comment] 2022-09-05 13:47
nah, it looks at date if there are multiple matches

**Comment by nebularg** [comment] 2024-03-11 02:55
Hopefully fixed with a8acbfa240184e20059e0a40ce5f4939c343bfde

**Closed by nebularg** 2024-03-11 02:55 UTC
